export const ActionTypes = {
 GET_STUDENT_RESULT: "GET_STUDENT_RESULT",
 GET_COURSE_REG: " GET_COURSE_REG",
 SUBMIT_COURSE_REG: "SUBMIT_COURSE_REG",
 AUTH_LOGIN_STUDENT: "AUTH_LOGIN_STUDENT",
 AUTH_LOGIN_STUDENT_ERROR: "AUTH_LOGIN_STUDENT_ERROR",
 SET_TO_TRUE: "SET_TO_TRUE",
 SET_TO_SUBMIT_TRUE: "SET_TO_SUBMIT_TRUE",
 Auth_Login_Student_Error: "Auth_Login_Student_Error"
}

